Ren PHP
Scouterna/simplesamlphp-module-scouterna-theme pull request #3
Opened 2019-11-06 23:05 UTC by puggan

* Converterat php-filerna till ren php,
* Flyttat upp all logik ovanför html outputen
* städat upp html-koden,
* ändrat från xhtml till html5

OBS nytjar PHP 7.3s version av HEREDOC, så kräver php 7.3+, 
men våra docker kör 7.3 så ansåg det ok.
(före php 7.3 kunde man inte indenter HEREDOC:s)

2019-11-07 18:43 UTC, Klako commented
Jag får detta felmeddelande efter att jag trycker på logga in: https://i.imgur.com/GhP56CS.png
Testade radera cookies och rensa memcache men det blev samma fel.

Har inte kollat igenom allt men det kanske är någon parameter som inte skickas med i formen.

2019-11-07 19:12 UTC, Klako requested changes
Efter ändringen verkar allt fungera.

2019-11-07 19:12 UTC, Klako commented on themes/feidernd/core/loginuserpass.php
> +                {$inputs}
`$inputs` kan inte konverteras till string, utan måste klistras ihop med [`join()`](https://www.php.net/manual/en/function.join.php) eller byggas som en string.

2019-11-08 08:36 UTC, puggan commented on themes/feidernd/core/loginuserpass.php
> +                {$inputs}
ska vara $inputsHtml, $inputs är en array, $inputsHtml är en sträng.
Borde blivit röd i editorn.

2019-11-08 09:15 UTC, puggan commented
Tack Klako, 
Har bytt till rätt variabel, och lagt en issue för att min editor ska varna om dessa fel :-)
https://github.com/kalessil/phpinspectionsea/issues/1445

2019-11-08 09:53 UTC, Klako approved these changes

2019-12-12 16:23 UTC, merged