Ändrad loginsida.
Scouterna/simplesamlphp-module-scouterna-theme pull request #4
Opened 2020-01-28 18:45 UTC by Klako

Ändrar loginsidan enligt scouterna/scoutid#52.

Nu står istället "Användarnamn" och en tooltip visar vilka namn som går att använda.
Frågan är om det är en bra idé att berätta om epostadressen eftersom det kräver en lite längre text.

Funkar och ser ok ut på mobil.

2020-01-30 14:31 UTC, puggan requested changes
Varför plockar du ut inputarna ur labels?
Då försvinner funktionen att man kan klicka på label-texten och den fokuserar på inputen.

2020-01-30 14:48 UTC, Klako commented
> Varför plockar du ut inputarna ur labels?
> Då försvinner funktionen att man kan klicka på label-texten och den fokuserar på inputen.

Ah. Tyckte det såg konstigt ut. Bör dock ha kollat hur labels funkar. c1b8a79

2020-01-31 03:34 UTC, puggan commented
Jag brukar lägga min text i en span, så ser det mer strukturerat ut, och så kan man lätt styla den med tex flex.
```
<label>
   <span>Text</span>
   <input type="text" />
</label>
```

Men for-attributet ska ju också funka. 👍

2020-01-31 03:34 UTC, puggan approved these changes

2020-01-31 03:35 UTC, puggan commented
Jag brukar lägga min text i en span, så ser det mer strukturerat ut, och så kan man lätt styla den med tex flex.
```
<label>
   <span>Text</span>
   <input type="text" />
</label>
```

Men for-attributet ska ju också funka. 👍

2020-01-31 13:44 UTC, merged